# docker-compose.yaml (for stage)
version: "3.7"
services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    init: true
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--global.sendAnonymousUsage=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.mycert.acme.httpchallenge=true"
      - "--certificatesresolvers.mycert.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.mycert.acme.email=infra@rakulang.net"
      - "--certificatesresolvers.mycert.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raku_redir.rule=Path(`/`)"
      - "traefik.http.routers.raku_redir.middlewares=to_https"
      - "traefik.http.middlewares.to_https.redirectscheme.scheme=https"

    restart: always
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # cert store
      - "/home/rancher/letsencrypt:/letsencrypt"

  rakubrew_org:
    image: docker.pkg.github.com/raku/rakubrew.org/rakubrew.org:latest
    init: true
    restart: unless-stopped 
    ports:
    - mode: host
      target: 10000
      published: 10000
    volumes:
      - "/home/rancher/rakubrew.org/releases:/releases:ro"
    depends_on:
      - "reverse-proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rakubrew_org.rule=Host(`rakubrew.org`) || Host(`www.rakubrew.org`)"
      - "traefik.http.routers.rakubrew_org.entrypoints=https"
      - "traefik.http.routers.rakubrew_org.tls.certresolver=mycert"

# end
